/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package my.project.irr.frame;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import my.project.irr.process.ProcessIRR;

/**
 *
 * @author junjun
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblHargaTunai = new javax.swing.JLabel();
        txtHargaTunai = new javax.swing.JTextField();
        lblDP = new javax.swing.JLabel();
        txtDP = new javax.swing.JTextField();
        lblAngsuran = new javax.swing.JLabel();
        txtAngsuran = new javax.swing.JTextField();
        lblCicilan = new javax.swing.JLabel();
        txtCicilan = new javax.swing.JTextField();
        btnHitung = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MainFrame");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHargaTunai.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblHargaTunai.setText("Harga Tunai");
        jPanel1.add(lblHargaTunai, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 80, 25));

        txtHargaTunai.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jPanel1.add(txtHargaTunai, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 160, 25));

        lblDP.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblDP.setText("DP");
        jPanel1.add(lblDP, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 80, 25));

        txtDP.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jPanel1.add(txtDP, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 160, 25));

        lblAngsuran.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblAngsuran.setText("Angsuran");
        jPanel1.add(lblAngsuran, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 80, 25));

        txtAngsuran.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jPanel1.add(txtAngsuran, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 160, 25));

        lblCicilan.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblCicilan.setText("Cicilan / Bulan");
        jPanel1.add(lblCicilan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 80, 25));

        txtCicilan.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jPanel1.add(txtCicilan, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 160, 25));

        btnHitung.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnHitung.setText("Hitung");
        btnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungActionPerformed(evt);
            }
        });
        jPanel1.add(btnHitung, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 70, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Aplikasi Leasing ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/project/irr/image/main-image.926621252_1.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 270));

        setSize(new java.awt.Dimension(700, 303));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
        try {
            double hargaTunai = Double.parseDouble(txtHargaTunai.getText());
            double dp = Double.parseDouble(txtDP.getText());
            double cicilan = Double.parseDouble(txtCicilan.getText());
            int angsuran = Integer.parseInt(txtAngsuran.getText());
            ProcessIRR hitung = new ProcessIRR(hargaTunai, dp, angsuran, cicilan);
            System.out.println("hikariiiiiiiiiiiiii");
            hitung.hitungIRR();
            System.out.println("=================---");
            ResultFrame result = new ResultFrame(hitung);
            System.out.println("=============8====---");
            result.setVisible(true);
            this.setVisible(false);
            System.out.println("================3=---");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "mohon input dengan benar");
        }

    }//GEN-LAST:event_btnHitungActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                try {
                     UIManager.setLookAndFeel("com.jtattoo.plaf.mcwin.McWinLookAndFeel");
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                    Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                    Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                } catch (UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
                new MainFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHitung;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAngsuran;
    private javax.swing.JLabel lblCicilan;
    private javax.swing.JLabel lblDP;
    private javax.swing.JLabel lblHargaTunai;
    private javax.swing.JTextField txtAngsuran;
    private javax.swing.JTextField txtCicilan;
    private javax.swing.JTextField txtDP;
    private javax.swing.JTextField txtHargaTunai;
    // End of variables declaration//GEN-END:variables
}
